# Generated by Django 6.0.4 on 2026-05-08 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_testdb_dataset_projectevaluation_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectevaluation",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projectevaluation",
            name="dataset",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="projects.dataset",
            ),
        ),
    ]
