# Generated by Django 6.0.4 on 2026-05-25 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_aboutsection_interest_sociallink_and_more"),
        ("projects", "0005_projectevaluation_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["is_featured", "-order", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="projects.tag"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="projects.technology"
            ),
        ),
        migrations.AlterField(
            model_name="projecthighlight",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s", to="projects.category"
            ),
        ),
        migrations.AlterField(
            model_name="projecthighlight",
            name="impact",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("highlights", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="projects/")),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("company_country", models.CharField(blank=True, max_length=100)),
                ("comments", models.TextField(blank=True)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="core.person",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="%(class)ss", to="projects.tag"
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True, related_name="%(class)ss", to="projects.technology"
                    ),
                ),
            ],
            options={
                "ordering": ["is_current", "-start_date", "-order"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("text", models.TextField(blank=True)),
                ("impact", models.CharField(blank=True, max_length=200)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="%(class)s", to="projects.category"
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_highlights",
                        to="projects.experience",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
