# Generated by Django 6.0.4 on 2026-06-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_options_alter_project_tags_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-is_featured", "order"]},
        ),
        migrations.RemoveField(
            model_name="experience",
            name="image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.AddField(
            model_name="experience",
            name="summary_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="summary_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
