services:
  web:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    platform: linux/arm64
    container_name: portfolio_web
    env_file:
      - .env
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - pdf-service

  pdf-service:
    build:
      context: ./pdf-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    
  db: 
    image: postgres:16
    container_name: portfolio_db
    restart: always

    environment: 
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_password
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"

volumes: 
  postgres_data:
  static_volume:
  media_volume:

