# Generated by Django 6.0.4 on 2026-05-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_person_options_remove_person_bio_profile_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Expertise",
            new_name="ExpertiseGroup",
        ),
        migrations.AddField(
            model_name="profile",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
