# Generated by Django 6.0.4 on 2026-05-17 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_expertise_expertisegroup_profile_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("url", models.URLField(max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["graduation"]},
        ),
        migrations.AlterModelOptions(
            name="expertisegroup",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="person",
            name="github_url",
        ),
        migrations.RemoveField(
            model_name="person",
            name="linkedin_url",
        ),
        migrations.AddField(
            model_name="expertisegroup",
            name="focus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertisegroup",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="about",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="about_title",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="focus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skill",
            name="level",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="core.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("person",),
                name="unique_active_profile_per_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                fields=("expertise", "name"), name="unique_skill_per_expertise"
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="abouts",
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="interest",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="core.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="interest",
            constraint=models.UniqueConstraint(
                fields=("profile", "name"), name="unique_interest_per_profile"
            ),
        ),
        migrations.AddConstraint(
            model_name="sociallink",
            constraint=models.UniqueConstraint(
                fields=("person", "platform"), name="unique_plataform_per_person"
            ),
        ),
    ]
