# Generated by Django 6.0.4 on 2026-06-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_aboutsection_interest_sociallink_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["-graduation"]},
        ),
        migrations.AddField(
            model_name="profile",
            name="cv_slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="EducationFocusArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.education",
                    ),
                ),
            ],
            options={
                "verbose_name": "Focus Area",
                "verbose_name_plural": "Focus Areas",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("education", "name"),
                        name="unique_focus_area_per_education",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EducationModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.education",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education Module",
                "verbose_name_plural": "Education Modules",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("education", "name"), name="unique_module_per_education"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "proficiency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("native", "Native"),
                            ("c1", "Fluent (C1)"),
                            ("b2", "Professional Working Proficiency (B2)"),
                            ("b1", "Intermediate (B1)"),
                            ("a2", "Elementary (A2)"),
                            ("a1", "Basic (A1)"),
                        ],
                        max_length=100,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="core.person",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "name"), name="unique_language_per_person"
                    )
                ],
            },
        ),
    ]
